out.println("<!DOCTYPE html>");
out.println("<html lang=\"en\">");
out.println("<head>");
out.println("<meta charset=\"UTF-8\">");
out.println("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
out.println("<title>Arc Coffee</title>");
out.println("<script src=\"script.js\"></script>");
out.println("<link rel=\"stylesheet\" href=\"styles.css\">");
out.println("</head>");

out.println("<body>");
out.println("<div id=\"navbar-container\"></div>");
out.println("<div class=\"image-container\">");
out.println("<!-- Background image -->");
out.println("<img src=\"shot1.jpeg\" alt=\"Background Image\" style=\"width: 100vw\">");
out.println("<div class=\"text-container\" style=\"top: 90%; left: 40%\">");
out.println("<a href=\"#\">Carefully curated, from worldwide.</a>");
out.println("</div>");
out.println("</div>");

out.println("<div class=\"content\" style=\"padding-left: 20px\">");

out.println("<h1 style=\"padding-left:50px\">Beans</h1>");

out.println("<div class=\"flex-container\" style=\"padding: 20px\">");
out.println("<!-- LEFT BLOCK FOR FILTERS -->");
out.println("<div class=\"flex-item-large\" style=\"height: 500px; overflow-y: auto\">");
out.println("<h3 style=\"margin: 25px; color: #441f12\">Filters</h3>");
out.println("<!-- Filter Options -->");
out.println("<div class=\"filter-option\">");
out.println("<label for=\"category\">Process:</label>");
out.println("<select id=\"category\">");
out.println("<option value=\"all\">All Processes</option>");
out.println("<option value=\"washed\">Washed</option>");
out.println("<option value=\"natural\">Natural</option>");
out.println("<option value=\"anaerobic\">Anaerobic</option>");
out.println("</select>");
out.println("</div>");
out.println("<div class=\"filter-option\">");
out.println("<label for=\"category\">Origin:</label>");
out.println("<select id=\"category\">");
out.println("<option value=\"all\">All Origins</option>");
out.println("<option value=\"colombia\">Colombia</option>");
out.println("<option value=\"kenya\">Ethiopia</option>");
out.println("<option value=\"peru\">Peru</option>");
out.println("<option value=\"blend\">Blend</option>");
out.println("</select>");
out.println("</div>");
out.println("</div>");
out.println("<!-- RIGHT BLOCK FOR SHOP ITEMS -->");
out.println("<div class=\"flex-item-large\" style=\"height: 250px; width: 66vw; margin-right: 25px; overflow-y: auto\">");
out.println("<!-- SHOP ITEMS -->");
out.println("<div class=\"flex-container\" style=\"padding: 32px\">");
out.println("<div class=\"flex-item-small\">");
out.println("<img src=\"bean.png\" alt=\"bean\" width=\"60px\" height=\"60px\" style=\"margin-top: 20px\">");
out.println("<h3>Bean 1</h3>");
out.println("</div>");
out.println("<div class=\"flex-item-small\">");
out.println("<img src=\"bean.png\" alt=\"bean\" width=\"60px\" height=\"60px\" style=\"margin-top: 20px\">");
out.println("<h3>Bean 2</h3>");
out.println("</div>");
out.println("<div class=\"flex-item-small\">");
out.println("<img src=\"bean.png\" alt=\"bean\" width=\"60px\" height=\"60px\" style=\"margin-top: 20px\">");
out.println("<h3>Bean 3</h3>");
out.println("</div>");
out.println("<div class=\"flex-item-small\">");
out.println("<img src=\"bean.png\" alt=\"bean\" width=\"60px\" height=\"60px\" style=\"margin-top: 20px\">");
out.println("<h3>Bean 4</h3>");
out.println("</div>");
out.println("</div>");
out.println("</div>");
out.println("</div>");
out.println("</div>");
out.println("</body>");
out.println("</html>");